'use client';

import { useState } from 'react';
import Link from 'next/link';

const faqItems = [
  { q: 'How do I become an author on 026Newsblog?', a: 'Submit an application through our Author Application page. You\'ll need to provide writing samples, a brief bio, and your area of expertise. Our editorial team reviews applications within 48 hours.' },
  { q: 'What\'s the minimum withdrawal amount?', a: 'Authors can withdraw earnings once they reach a minimum balance of $50 USD (approximately KES 6,465). Withdrawals are processed via M-Pesa within 24 hours.' },
  { q: 'How does the revenue split work?', a: 'Authors receive 70% of the revenue generated by their content through ads and engagement. 026Newsblog retains 30% to cover platform costs, hosting, and development.' },
  { q: 'Can I republish my articles elsewhere?', a: 'Yes. You retain full ownership of your content. We recommend waiting 7 days after publishing on 026Newsblog before republishing elsewhere to maximize SEO benefits on our platform.' },
  { q: 'How do I report inappropriate content?', a: 'Use the report button on any comment or article, or email moderation@026newsblog.com. Our AI moderation system also auto-flags potentially harmful content for human review.' },
];

export default function ContactPage() {
  const [openFaq, setOpenFaq] = useState<number | null>(null);

  return (
    <div style={{ maxWidth: 1000, margin: '0 auto', padding: '56px 24px 80px' }}>
      <div style={{ textAlign: 'center', marginBottom: 48 }}>
        <h1 style={{ fontSize: '2rem', fontWeight: 700, letterSpacing: '-0.02em', marginBottom: 8 }}>Get in Touch</h1>
        <p style={{ fontSize: '0.95rem', color: 'var(--text-secondary)', maxWidth: 50, margin: '0 auto' }}>Questions, partnerships, advertising, or press inquiries. We&apos;d love to hear from you.</p>
      </div>

      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: 16, marginBottom: 48 }}>
        {[
          { icon: '📧', title: 'General Inquiries', desc: 'Questions about the platform, feedback, or suggestions', email: 'hello@026newsblog.com' },
          { icon: '📢', title: 'Advertising', desc: 'Sponsored content, display ads, and brand partnerships', email: 'ads@026newsblog.com' },
          { icon: '🎤', title: 'Press & Media', desc: 'Interview requests, press releases, media kits', email: 'press@026newsblog.com' },
        ].map((card) => (
          <div key={card.title} style={{ padding: 28, background: 'var(--bg-surface)', border: '1px solid var(--border-subtle)', borderRadius: 14, textAlign: 'center' }}>
            <div style={{ fontSize: '2rem', marginBottom: 12 }}>{card.icon}</div>
            <div style={{ fontSize: '0.92rem', fontWeight: 700, marginBottom: 4 }}>{card.title}</div>
            <div style={{ fontSize: '0.78rem', color: 'var(--text-tertiary)', marginBottom: 12 }}>{card.desc}</div>
            <a href={`mailto:${card.email}`} style={{ fontSize: '0.82rem', color: 'var(--primary)', textDecoration: 'none', fontWeight: 600 }}>{card.email}</a>
          </div>
        ))}
      </div>

      <div style={{ display: 'grid', gridTemplateColumns: '1fr 340px', gap: 40 }}>
        <div style={{ background: 'var(--bg-surface)', border: '1px solid var(--border-subtle)', borderRadius: 16, padding: 36 }}>
          <h2 style={{ fontSize: '1.2rem', fontWeight: 700, marginBottom: 4 }}>Send us a message</h2>
          <p style={{ fontSize: '0.82rem', color: 'var(--text-tertiary)', marginBottom: 28 }}>We typically respond within 24 hours on business days.</p>
          <form onSubmit={(e) => e.preventDefault()}>
            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 14, marginBottom: 18 }}>
              <div><label style={{ fontSize: '0.78rem', fontWeight: 600, color: 'var(--text-secondary)', marginBottom: 6, display: 'block' }}>First Name</label><input placeholder="Wayne" style={inputStyle} /></div>
              <div><label style={{ fontSize: '0.78rem', fontWeight: 600, color: 'var(--text-secondary)', marginBottom: 6, display: 'block' }}>Last Name</label><input placeholder="Nyamu" style={inputStyle} /></div>
            </div>
            <div style={{ marginBottom: 18 }}><label style={{ fontSize: '0.78rem', fontWeight: 600, color: 'var(--text-secondary)', marginBottom: 6, display: 'block' }}>Email</label><input type="email" placeholder="you@example.com" style={inputStyle} /></div>
            <div style={{ marginBottom: 18 }}><label style={{ fontSize: '0.78rem', fontWeight: 600, color: 'var(--text-secondary)', marginBottom: 6, display: 'block' }}>Subject</label>
              <select style={{ ...inputStyle, appearance: 'none', backgroundImage: "url(\"data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='12' height='12' viewBox='0 0 24 24' fill='none' stroke='%23888' stroke-width='2'%3E%3Cpolyline points='6 9 12 15 18 9'/%3E%3C/svg%3E\")", backgroundRepeat: 'no-repeat', backgroundPosition: 'right 12px center', cursor: 'pointer' as const }}>
                <option>General Inquiry</option><option>Advertising & Partnerships</option><option>Author Application</option><option>Technical Support</option><option>Bug Report</option><option>Press & Media</option><option>Legal</option>
              </select>
            </div>
            <div style={{ marginBottom: 18 }}><label style={{ fontSize: '0.78rem', fontWeight: 600, color: 'var(--text-secondary)', marginBottom: 6, display: 'block' }}>Message</label><textarea placeholder="Tell us how we can help..." rows={5} style={{ ...inputStyle, resize: 'vertical' as const, minHeight: 120, lineHeight: 1.5 }} /></div>
            <button type="submit" style={{ padding: '12px 24px', borderRadius: 9, fontSize: '0.85rem', fontWeight: 600, cursor: 'pointer', fontFamily: 'inherit', background: 'var(--primary)', color: 'oklch(98% 0.005 175)', border: 'none', width: '100%', display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 8 }}>Send Message</button>
          </form>
        </div>

        <div style={{ display: 'flex', flexDirection: 'column', gap: 20 }}>
          <div style={{ padding: 24, background: 'var(--bg-surface)', border: '1px solid var(--border-subtle)', borderRadius: 14 }}>
            <h3 style={{ fontSize: '0.92rem', fontWeight: 700, marginBottom: 8 }}>Advertise with Us</h3>
            <p style={{ fontSize: '0.82rem', color: 'var(--text-secondary)', lineHeight: 1.5, marginBottom: 12 }}>Reach East Africa&apos;s most engaged tech and business audience.</p>
            <div style={{ display: 'flex', gap: 16, marginBottom: 12 }}>
              <div style={{ flex: 1, textAlign: 'center', padding: '12px 8px', background: 'var(--bg-inset)', borderRadius: 9 }}><div style={{ fontSize: '1.1rem', fontWeight: 700, color: 'var(--primary)' }}>284K</div><div style={{ fontSize: '0.65rem', color: 'var(--text-tertiary)', marginTop: 2 }}>Monthly Views</div></div>
              <div style={{ flex: 1, textAlign: 'center', padding: '12px 8px', background: 'var(--bg-inset)', borderRadius: 9 }}><div style={{ fontSize: '1.1rem', fontWeight: 700, color: 'var(--primary)' }}>6.8%</div><div style={{ fontSize: '0.65rem', color: 'var(--text-tertiary)', marginTop: 2 }}>Engagement</div></div>
            </div>
            <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
              {[
                { icon: '📰', name: 'Sponsored Article', desc: 'Native content by our writers', price: 'From $500' },
                { icon: '🎯', name: 'Display Ads', desc: 'Banner placements on feed', price: 'From $200/wk' },
                { icon: '📧', name: 'Newsletter Sponsor', desc: 'Featured in daily digest', price: 'From $150' },
                { icon: '📌', name: 'Homepage Feature', desc: 'Hero slot for 24 hours', price: 'From $800' },
              ].map((opt) => (
                <div key={opt.name} style={{ display: 'flex', alignItems: 'center', gap: 10, padding: 12, background: 'var(--bg-inset)', borderRadius: 9 }}>
                  <span style={{ fontSize: '1.2rem' }}>{opt.icon}</span>
                  <div style={{ flex: 1 }}><div style={{ fontSize: '0.8rem', fontWeight: 600 }}>{opt.name}</div><div style={{ fontSize: '0.68rem', color: 'var(--text-tertiary)' }}>{opt.desc}</div></div>
                  <span style={{ fontSize: '0.78rem', fontWeight: 700, color: 'var(--primary)' }}>{opt.price}</span>
                </div>
              ))}
            </div>
          </div>

          <div style={{ padding: 24, background: 'var(--bg-surface)', border: '1px solid var(--border-subtle)', borderRadius: 14 }}>
            <h3 style={{ fontSize: '0.92rem', fontWeight: 700, marginBottom: 8 }}>Our Audience</h3>
            <p style={{ fontSize: '0.82rem', color: 'var(--text-secondary)', lineHeight: 1.5, marginBottom: 12 }}>Tech professionals, entrepreneurs, investors, and decision-makers across East Africa aged 22-45.</p>
            <div style={{ display: 'flex', gap: 16 }}>
              <div style={{ flex: 1, textAlign: 'center', padding: '12px 8px', background: 'var(--bg-inset)', borderRadius: 9 }}><div style={{ fontSize: '1.1rem', fontWeight: 700, color: 'var(--primary)' }}>73%</div><div style={{ fontSize: '0.65rem', color: 'var(--text-tertiary)', marginTop: 2 }}>Mobile</div></div>
              <div style={{ flex: 1, textAlign: 'center', padding: '12px 8px', background: 'var(--bg-inset)', borderRadius: 9 }}><div style={{ fontSize: '1.1rem', fontWeight: 700, color: 'var(--primary)' }}>68%</div><div style={{ fontSize: '0.65rem', color: 'var(--text-tertiary)', marginTop: 2 }}>Kenya</div></div>
            </div>
          </div>
        </div>
      </div>

      <div style={{ marginTop: 48 }}>
        <h2 style={{ fontSize: '1.2rem', fontWeight: 700, marginBottom: 20, textAlign: 'center' }}>Frequently Asked Questions</h2>
        <div style={{ display: 'flex', flexDirection: 'column', gap: 10, maxWidth: 700, margin: '0 auto' }}>
          {faqItems.map((item, i) => (
            <div key={i} onClick={() => setOpenFaq(openFaq === i ? null : i)} style={{ padding: '18px 20px', background: 'var(--bg-surface)', border: '1px solid var(--border-subtle)', borderRadius: 12, cursor: 'pointer' }}>
              <div style={{ fontSize: '0.88rem', fontWeight: 600, display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                {item.q}
                <span style={{ fontSize: '1.2rem', color: 'var(--text-tertiary)' }}>{openFaq === i ? '−' : '+'}</span>
              </div>
              {openFaq === i && <p style={{ fontSize: '0.82rem', color: 'var(--text-secondary)', lineHeight: 1.6, marginTop: 12 }}>{item.a}</p>}
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}

const inputStyle: React.CSSProperties = {
  width: '100%',
  padding: '11px 14px',
  borderRadius: 9,
  border: '1px solid var(--border)',
  background: 'var(--bg-elevated)',
  color: 'var(--text-primary)',
  fontSize: '0.85rem',
  fontFamily: 'inherit',
  outline: 'none',
  boxSizing: 'border-box' as const,
};
